// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2025-2026 gotnull (developer@socialmesh.app)

import 'dart:io';

const defaultClientEnvSource = '.env';
const defaultClientEnvOutput = '.env.client';
const defaultClientEnvAllowlist = 'config/client_env_allowlist.txt';

/// Server/deployment configuration that must never enter a client artifact.
const prohibitedClientEnvKeys = <String>{
  'ADMIN_UIDS',
  'API_BASE_URL',
  'CLOUDFLARE_API_TOKEN',
  'CLOUD_SYNC_MONTHLY_PRODUCT_ID',
  'CLOUD_SYNC_YEARLY_PRODUCT_ID',
  'ENT_ID',
  'FIREBASE_ANDROID_APP_ID',
  'FIREBASE_IOS_APP_ID',
  'FIREBASE_IOS_BUNDLE_ID',
  'FIREBASE_PROJECT_ID',
  'FLAGS_LOGGING_ENABLED',
  'FREESCOUT_PASSWORD',
  'FREESCOUT_USERNAME',
  'GMAIL_APP_PASSWORD',
  'GMAIL_IMAP_EMAIL',
  'GMAIL_IMAP_PORT',
  'GMAIL_IMAP_SERVER',
  'INCIDENT_FUNCTIONS_LOGGING_ENABLED',
  'OPENSKY_PROXY_KEY',
  'OPENSKY_PROXY_URL',
  'ROLE_VALIDATION_LOGGING_ENABLED',
};

final RegExp _envAssignmentPattern = RegExp(r'^([A-Za-z_][A-Za-z0-9_]*)=(.*)$');
final RegExp _envKeyPattern = RegExp(r'^[A-Za-z_][A-Za-z0-9_]*$');
final RegExp _directDotenvReadPattern = RegExp(
  r'''dotenv\.(?:env\[|get\(|maybeGet\()\s*['"]([A-Za-z_][A-Za-z0-9_]*)['"]''',
  multiLine: true,
);
final RegExp _dotenvHelperReadPattern = RegExp(
  r'''(?:_safeGetEnv|_parseBoolEnv|_readBool|_readBoolOrNull|_readBoolDefaultTrue|_readBoolDefaultFalse)\(\s*['"]([A-Za-z_][A-Za-z0-9_]*)['"]''',
  multiLine: true,
);

Set<String> parseClientEnvAllowlist(String contents) {
  final keys = <String>{};
  for (final rawLine in contents.split('\n')) {
    final line = rawLine.trim();
    if (line.isEmpty || line.startsWith('#')) continue;
    if (!_envKeyPattern.hasMatch(line)) {
      throw FormatException('Invalid client env allowlist key: $line');
    }
    if (!keys.add(line)) {
      throw FormatException('Duplicate client env allowlist key: $line');
    }
  }

  final prohibited = keys.intersection(prohibitedClientEnvKeys);
  if (prohibited.isNotEmpty) {
    throw FormatException(
      'Client env allowlist contains prohibited server configuration: '
      '${prohibited.toList()..sort()}',
    );
  }
  return keys;
}

Set<String> discoverProductionClientEnvKeys(Directory libDirectory) {
  final keys = <String>{};
  for (final entity in libDirectory.listSync(recursive: true)) {
    if (entity is! File || !entity.path.endsWith('.dart')) continue;
    final contents = entity.readAsStringSync();
    for (final pattern in [
      _directDotenvReadPattern,
      _dotenvHelperReadPattern,
    ]) {
      for (final match in pattern.allMatches(contents)) {
        keys.add(match.group(1)!);
      }
    }
  }
  return keys;
}

String generateClientEnv({
  required String sourceContents,
  required Set<String> allowlist,
}) {
  final assignments = <String, String>{};
  for (final rawLine in sourceContents.split('\n')) {
    final match = _envAssignmentPattern.firstMatch(rawLine);
    if (match == null) continue;

    final key = match.group(1)!;
    if (assignments.containsKey(key)) {
      throw FormatException('Duplicate key in source env: $key');
    }
    assignments[key] = match.group(2)!;
  }

  final output = StringBuffer(
    '# Generated by tool/generate_client_env.dart. Do not edit or commit.\n',
  );
  final includedKeys = assignments.keys.where(allowlist.contains).toList()
    ..sort();
  for (final key in includedKeys) {
    output.writeln('$key=${assignments[key]}');
  }
  return output.toString();
}

void main(List<String> args) {
  final checkOnly = args.contains('--check');
  final sourceFile = File(defaultClientEnvSource);
  final outputFile = File(defaultClientEnvOutput);
  final allowlistFile = File(defaultClientEnvAllowlist);

  try {
    if (!sourceFile.existsSync()) {
      throw FileSystemException('Source env file is missing', sourceFile.path);
    }
    if (!allowlistFile.existsSync()) {
      throw FileSystemException(
        'Client env allowlist is missing',
        allowlistFile.path,
      );
    }

    final allowlist = parseClientEnvAllowlist(allowlistFile.readAsStringSync());
    final discoveredKeys = discoverProductionClientEnvKeys(Directory('lib'));
    final missingFromAllowlist = discoveredKeys.difference(allowlist);
    if (missingFromAllowlist.isNotEmpty) {
      throw StateError(
        'Production dotenv keys require allowlist review: '
        '${missingFromAllowlist.toList()..sort()}',
      );
    }
    final generated = generateClientEnv(
      sourceContents: sourceFile.readAsStringSync(),
      allowlist: allowlist,
    );

    if (checkOnly) {
      if (!outputFile.existsSync() ||
          outputFile.readAsStringSync() != generated) {
        throw StateError(
          '${outputFile.path} is missing or stale; run '
          'dart run tool/generate_client_env.dart',
        );
      }
    } else {
      outputFile.writeAsStringSync(generated, flush: true);
    }

    final generatedCount = generated
        .split('\n')
        .where((line) => _envAssignmentPattern.hasMatch(line))
        .length;
    stdout.writeln(
      '${checkOnly ? 'Verified' : 'Generated'} ${outputFile.path} with '
      '$generatedCount allowlisted keys.',
    );
  } catch (error) {
    stderr.writeln('Client env generation failed: $error');
    exitCode = 1;
  }
}
